import Head from 'next/head'
import MainLayout from '../components/layouts/MainLayout'
import Collection1 from '../components/Collections/Collection1/Collection1'
import Collection3 from '../components/Collections/Collection3/Collection3'

export default function Collections() {
  return (
    <MainLayout>
      <Head>
        <title>MMG Themes</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 style={{ padding: '2rem', textAlign: 'center' }}>All Collections</h1>
      <div className='comp-space'>
        <Collection1 />
      </div>
      <div className='comp-space'>
        <Collection3 />
      </div>
    </MainLayout>
  )
}
