import React from 'react'
import Head from 'next/head'
import ShowLayout from '../components/layouts/ShowLayout'
import Header1 from '../components/Header/Header1/Header1'
import Header2 from '../components/Header/Header2/Header2'
import Header3 from '../components/Header/Header3/Header3'
import AnnouncementBar from '../components/AnnouncementBar/AnnouncementBar'

export default function Headers() {
  return (
    <ShowLayout>
      <Head>
        <title>MMG THEMES - All Avaliable Headers</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 style={{ padding: '2rem', textAlign: 'center' }}>All Headers</h1>
      <div className='comp-space'>
        <AnnouncementBar />
        <Header1 />
      </div>
      <div className='comp-space'>
        <Header2 />
      </div>
      <div className='comp-space'>
        <Header3 />
      </div>
    </ShowLayout>
  )
}
