import React from 'react'
import Head from 'next/head'
import ShowLayout from '../components/layouts/ShowLayout'
import Hero1 from '../components/Heros/Hero1/Hero1'
import Hero2 from '../components/Heros/Hero2/Hero2'

export default function Heros() {
  return (
    <ShowLayout>
      <Head>
        <title>MMG THEMES - All Avaliable Heros</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 style={{ padding: '2rem', textAlign: 'center' }}>All Heros</h1>
      <div className='comp-space'>
        <Hero1 />
      </div>
      <div className='comp-space'>
        <Hero2 />
      </div>
    </ShowLayout>
  )
}
